### ISSUE TITLE
what does the `excepList` means in the extractDirectSyscalls() of containerProfiler.py？

### ISSUE THREAD

**Issue by DawnGuoDev** [shamedgh/confine#10]
What does the `excepList = ["ld.so", "libc.so", "libdl.so", "libcrypt.so", "libnss_compat.so", "libnsl.so", "libnss_files.so", "libnss_nis.so", "libpthread.so", "libm.so", "libresolv.so", "librt.so", "libutil.so", "libnss_dns.so", "gosu"]` means?  Does it means that the glibc.callgraph contains the callgraph of ld.so or libdl.so?

**Comment by shamedgh** [comment]
Yes! These libraries are installed with the glibc package and we expect them to be considered when we build the glibc callgraph. Please comment if you find any discrepancies.
