### ISSUE TITLE
issue on callgraph

### ISSUE THREAD

**Issue by 1737g** [shamedgh/confine#2]
Generating call graph from glibc source is quite a headache.
I'm not quite sure how come almost all function has the same mapped syscalls in the same order.  Is this a common sense?
For example:
`
malloc:syscall ( 96 )
malloc:syscall ( 2 )
malloc:syscall ( 166 )
malloc:syscall ( 134 )
malloc:syscall ( 201 )
malloc:syscall ( 330 )
malloc:syscall ( 331 )
malloc:syscall ( 174 )
malloc:syscall ( 15 )
malloc:syscall ( 177 )
malloc:syscall ( 178 )
malloc:syscall ( 180 )
malloc:syscall ( 58 )
malloc:syscall ( 319 )
`

**Comment by shamedgh** [comment]
Due to overapproximations in generating the callgraph it is expected that some functions get mapped to unrelated system calls. Unless there's an edge missing, we do not consider having extra edges a problem. Although there could be ways to reduce the overapproximation.
